// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TapeReelPacking.Source.Model;

namespace TapeReelPacking.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240818174857_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TapeReelPacking.Source.Model.CategoryTeachParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DR_DefectROIIndex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DR_NumberROILocation")
                        .HasColumnType("int");

                    b.Property<int>("L_CornerIndex")
                        .HasColumnType("int");

                    b.Property<string>("L_DeviceLocationRoi")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("L_DilationMask")
                        .HasColumnType("int");

                    b.Property<bool>("L_LocationEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("L_MinHeightDevice")
                        .HasColumnType("int");

                    b.Property<double>("L_MinScore")
                        .HasColumnType("double");

                    b.Property<int>("L_MinWidthDevice")
                        .HasColumnType("int");

                    b.Property<int>("L_NumberSide")
                        .HasColumnType("int");

                    b.Property<string>("L_ObjectColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("L_OpeningMask")
                        .HasColumnType("int");

                    b.Property<double>("L_ScaleImageRatio")
                        .HasColumnType("double");

                    b.Property<int?>("L_TemplateRoiId")
                        .HasColumnType("int");

                    b.Property<string>("L_ThresholdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("L_lowerThreshold")
                        .HasColumnType("int");

                    b.Property<int>("L_lowerThresholdInnerChip")
                        .HasColumnType("int");

                    b.Property<int>("L_upperThreshold")
                        .HasColumnType("int");

                    b.Property<int>("L_upperThresholdInnerChip")
                        .HasColumnType("int");

                    b.Property<int>("OC_DilationMask")
                        .HasColumnType("int");

                    b.Property<int>("OC_MinHeightDevice")
                        .HasColumnType("int");

                    b.Property<int>("OC_MinWidthDevice")
                        .HasColumnType("int");

                    b.Property<int>("OC_OpeningMask")
                        .HasColumnType("int");

                    b.Property<int>("OC_lowerThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("L_TemplateRoiId");

                    b.ToTable("userlogins");
                });

            modelBuilder.Entity("TapeReelPacking.Source.Model.RectanglesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Angle")
                        .HasColumnType("double");

                    b.Property<double>("Height")
                        .HasColumnType("double");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.Property<double>("left")
                        .HasColumnType("double");

                    b.Property<double>("top")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("rectanglesModel");
                });

            modelBuilder.Entity("TapeReelPacking.Source.Model.CategoryTeachParameter", b =>
                {
                    b.HasOne("TapeReelPacking.Source.Model.RectanglesModel", "L_TemplateRoi")
                        .WithMany()
                        .HasForeignKey("L_TemplateRoiId");
                });
#pragma warning restore 612, 618
        }
    }
}
