// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TapeReelPacking.Source.Model;

namespace TapeReelPacking.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240818175307_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TapeReelPacking.Source.Model.RectanglesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Angle")
                        .HasColumnType("double");

                    b.Property<double>("Height")
                        .HasColumnType("double");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.Property<double>("left")
                        .HasColumnType("double");

                    b.Property<double>("top")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("rectanglesModel");
                });
#pragma warning restore 612, 618
        }
    }
}
